import { useParams } from "react-router-dom";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ContactForm } from "@/components/ContactForm";
import { Button } from "@/components/ui/button";
import { ShieldCheck, Lock, Database, FileCheck, Activity, Download } from "lucide-react";

const VerifyReport = () => {
  const { code = "8Z8G-MRJB" } = useParams();

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-16">
        {/* Verified bar */}
        <div className="bg-primary/95 text-white">
          <div className="container py-3 flex flex-wrap items-center justify-between gap-3 text-sm">
            <div className="flex items-center gap-3">
              <span className="inline-flex items-center gap-1.5 bg-accent px-3 py-1 rounded-full text-xs font-bold">
                <ShieldCheck className="h-3.5 w-3.5" /> VERIFIED & SECURED
              </span>
              <span className="font-mono text-white/90">verify.helixanalyticals.com/{code}</span>
            </div>
            <div className="inline-flex items-center gap-2 text-xs text-white/80">
              <Lock className="h-3.5 w-3.5" /> 256-bit TLS Encrypted
            </div>
          </div>
        </div>

        <section className="py-12 md:py-16 bg-gradient-verify">
          <div className="container max-w-6xl grid lg:grid-cols-2 gap-10 items-start">
            {/* Digital COA card */}
            <div className="rounded-2xl bg-card border border-border p-6 md:p-8 shadow-elegant">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-2">
                  <div className="h-8 w-8 rounded-lg bg-gradient-primary flex items-center justify-center">
                    <ShieldCheck className="h-4 w-4 text-white" />
                  </div>
                  <div>
                    <div className="text-xs font-mono uppercase tracking-wider text-primary">HelixVerify™ Digital COA</div>
                    <div className="text-xs text-muted-foreground">helixanalyticals.com</div>
                  </div>
                </div>
                <span className="text-xs font-bold text-accent bg-accent/10 px-3 py-1 rounded-full">CONFORMS</span>
              </div>
              <div className="text-xs uppercase tracking-wider text-muted-foreground mb-1">Peptide</div>
              <div className="text-2xl font-bold mb-6">TB500 (17-23 Fragment)</div>
              <div className="text-xs uppercase tracking-wider text-muted-foreground mb-1">Client / Batch / Lot</div>
              <div className="text-sm font-medium mb-6">Harmony Peptide · TB10 · LOT TB10HYBCBC</div>
              <div className="grid grid-cols-3 gap-3 mb-6">
                {[
                  { l: "Purity", v: "99.77%", ok: "Conforms" },
                  { l: "Identity", v: "TB500", ok: "Conforms" },
                  { l: "Quantity", v: "10.08 mg", ok: "Conforms" },
                ].map((m) => (
                  <div key={m.l} className="rounded-lg bg-secondary/60 p-3">
                    <div className="text-xs text-muted-foreground mb-1">{m.l}</div>
                    <div className="font-bold">{m.v}</div>
                    <div className="inline-flex items-center gap-1 text-[10px] text-accent mt-1">● {m.ok}</div>
                  </div>
                ))}
              </div>
              <div className="border-t border-border pt-4 flex justify-between items-center text-xs font-mono text-muted-foreground">
                <span>{code}</span>
                <span>MAR 6, 2026</span>
              </div>
            </div>

            {/* Status */}
            <div>
              <div className="flex items-start gap-4 mb-8">
                <div className="h-14 w-14 rounded-full bg-accent/20 flex items-center justify-center shrink-0">
                  <ShieldCheck className="h-7 w-7 text-accent" />
                </div>
                <div>
                  <div className="text-sm text-muted-foreground">HelixVerify™</div>
                  <h1 className="text-3xl md:text-4xl font-bold text-accent">Authenticity Confirmed</h1>
                  <p className="text-muted-foreground mt-2">This result was generated by HelixAnalyticals and has not been altered.</p>
                </div>
              </div>
              <div className="rounded-xl bg-card border border-border p-4 mb-4 shadow-soft">
                <div className="text-xs uppercase text-muted-foreground">Report ID</div>
                <div className="font-mono text-lg font-bold">{code}</div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                {[
                  { l: "Client", v: "Harmony Peptide" },
                  { l: "Batch / Lot", v: "TB10HYBCBC" },
                  { l: "Sample Received", v: "Mar 6, 2026" },
                  { l: "Analysis Completed", v: "Mar 6, 2026" },
                ].map((c) => (
                  <div key={c.l} className="rounded-xl bg-card border border-border p-4 shadow-soft">
                    <div className="text-xs uppercase text-muted-foreground">{c.l}</div>
                    <div className="font-semibold mt-1">{c.v}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Core panel results */}
        <section className="py-16">
          <div className="container max-w-6xl">
            <div className="rounded-2xl bg-card border border-border p-6 md:p-8 shadow-soft mb-8">
              <div className="flex items-center gap-2 mb-6">
                <Activity className="h-5 w-5 text-primary" />
                <h2 className="text-xl font-bold">Core Panel Results</h2>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground">
                      <th className="text-left py-3 font-medium">Test</th>
                      <th className="text-left py-3 font-medium">Result</th>
                      <th className="text-left py-3 font-medium">Specification</th>
                      <th className="text-left py-3 font-medium">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      ["TB500 (17-23 Fragment) - Purity", "99.77%", "> 98.0%", "Conforms"],
                      ["TB500 (17-23 Fragment) - Identity", "TB500 (17-23 Fragment)", "TB500 (17-23 Fragment)", "Conforms"],
                      ["TB500 (17-23 Fragment) - Quantity", "10.08 mg", "MEASURED", "Measured"],
                    ].map((r) => (
                      <tr key={r[0]} className="border-b border-border last:border-0">
                        <td className="py-4">{r[0]}</td>
                        <td className="py-4 font-mono">{r[1]}</td>
                        <td className="py-4 text-muted-foreground">{r[2]}</td>
                        <td className="py-4">
                          <span className="inline-flex items-center gap-1 bg-accent/10 text-accent text-xs px-2.5 py-1 rounded-full font-semibold">
                            ✓ {r[3]}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Chromatogram placeholder */}
            <div className="rounded-2xl bg-card border border-border p-6 md:p-8 shadow-soft mb-8">
              <div className="flex items-center gap-2 mb-6">
                <Activity className="h-5 w-5 text-primary" />
                <h2 className="text-xl font-bold">HPLC Chromatogram</h2>
              </div>
              <div className="relative h-72 rounded-xl bg-secondary/40 border border-border overflow-hidden">
                <svg viewBox="0 0 800 250" className="absolute inset-0 w-full h-full" preserveAspectRatio="none">
                  <text x="20" y="25" className="text-xs fill-current text-primary" fontFamily="monospace" fontSize="12">DAD1A,Sig=220.0,4.0 Ref=360.0,100.0</text>
                  <line x1="40" y1="220" x2="780" y2="220" stroke="hsl(var(--border))" />
                  <line x1="40" y1="20" x2="40" y2="220" stroke="hsl(var(--border))" />
                  <polyline
                    fill="none"
                    stroke="hsl(var(--primary))"
                    strokeWidth="1.5"
                    points="40,215 120,213 200,212 280,210 320,208 360,80 380,30 400,80 440,205 520,210 600,212 680,213 780,215"
                  />
                  <text x="385" y="20" fontSize="10" fontFamily="monospace" fill="hsl(var(--primary))">5.528</text>
                </svg>
                <div className="absolute bottom-3 right-4 text-xs text-muted-foreground font-mono">mAU vs minutes</div>
              </div>
            </div>

            {/* Verification details */}
            <div className="grid md:grid-cols-2 gap-6">
              <div className="rounded-2xl bg-card border border-border p-6 shadow-soft">
                <h3 className="font-bold mb-4 flex items-center gap-2"><FileCheck className="h-5 w-5 text-primary" /> HelixVerify™ Digital Verification</h3>
                <dl className="space-y-3 text-sm">
                  <div><dt className="text-muted-foreground text-xs uppercase">Report ID</dt><dd className="font-mono font-semibold">{code}</dd></div>
                  <div><dt className="text-muted-foreground text-xs uppercase">Verification URL</dt><dd className="font-mono text-primary break-all">verify.helixanalyticals.com/{code}</dd></div>
                  <div><dt className="text-muted-foreground text-xs uppercase">Verified</dt><dd>Mar 6, 2026 · 21:48:58 UTC</dd></div>
                  <div><dt className="text-muted-foreground text-xs uppercase">Data Source</dt><dd>HelixAnalyticals LIMS</dd></div>
                </dl>
                <div className="mt-4 pt-4 border-t border-border text-xs text-muted-foreground">
                  <strong className="text-foreground">Laboratory:</strong> HelixAnalyticals · <strong className="text-foreground">Lab ID:</strong> VPL-001
                </div>
                <Button variant="outline" className="mt-5 w-full"><Download className="h-4 w-4" /> Download PDF</Button>
              </div>

              <div className="space-y-4">
                {[
                  { icon: Database, t: "LIMS Data", b: "This report was rendered unaltered from our LIMS. There's no file to edit or swap." },
                  { icon: Lock, t: "Immutable Record", b: "Result hash anchored to blockchain at time of finalization." },
                  { icon: ShieldCheck, t: "Tamper-Evident", b: "Any alteration would break the cryptographic verification chain." },
                ].map((f) => (
                  <div key={f.t} className="rounded-xl bg-card border border-border p-4 flex gap-3 shadow-soft">
                    <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                      <f.icon className="h-4 w-4 text-primary" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-sm">{f.t}</h4>
                      <p className="text-xs text-muted-foreground mt-0.5">{f.b}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <ContactForm />
      </main>
      <Footer />
    </div>
  );
};

export default VerifyReport;
